env:
  TERM: alacritty

window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 6
    y: 6

  dynamic_padding: true
  decorations: buttonless
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true
  opacity: 0.92

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono
    style: Bold Italic

  size: 16.0

  glyph_offset:
    y: 1

  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#21272a'
    foreground: '#d8dee9'

  selection:
    text: '#d8dee9'
    background: '#434c5e'

  normal:
    black:   '#2e3440'
    red:     '#bf616a'
    green:   '#a3be8c'
    yellow:  '#ebcb8b'
    blue:    '#5e81ac'
    magenta: '#b48ead'
    cyan:    '#88c0d0'
    white:   '#d8dee9'

  bright:
    black:   '#4c566a'
    red:     '#fa9ea7'
    green:   '#d8f2c2'
    yellow:  '#ffe1a5'
    blue:    '#81a1c1'
    magenta: '#d5abcd'
    cyan:    '#cdfcfa'
    white:   '#eceff4'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: Never
  unfocused_hollow: true

live_config_reload: true

mouse:
  hide_when_typing: true
