#!/bin/bash
# Wrap commands that interact with the Heroku CLI and set the TERM variable to
# xterm, since Alacritty isn't a supported terminal type

production() {
  TERM=xterm command production "$@"
}
